# Separate docker compose for LinguaSynth
services:
  backend:
    container_name: linguaSynth
    build: .
    ports:
      - "8000:${LINGUASYNTH_PORT}"
    environment:
      - UVICORN_RELOAD=true
    volumes:
      - ./app:/app
    tty: true
