# Compose file for the ollama LLM service
services:
  ollama:
    image: ollama/ollama:0.11.8
    container_name: "ollama_server"
    restart: on-failure
    ports:
      - "11434:${OLLAMA_PORT}"
    volumes:
      - ./data:/root/.ollama
    networks:
      - private
