name: pipeline
on:
  pull_request:
    branches:
      - 'Development'
  push:
    branches:
      - 'Development'

jobs:
  deploy:
    name: build & push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'Development'

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./Backend/docker-compose.yml"

      # - name: Execute tests in the running services
      #   run: |
      #     docker compose exec test-app pytest